### ISSUE TITLE
+Android Basics: Coroutines

### ISSUE THREAD

**Issue by ornolisvt** [google-developer-training/android-basics-kotlin-mars-photos-app#54] opened 2021-06-15 03:59 UTC
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-04-14 22:50
@ornolisvt 
The issue is closed as no further clarification of it was provided.

**Closed as completed by osuleymanova** 2022-04-14 22:50 UTC
