### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by KKH-tw** [google-developer-training/android-basics-kotlin-mars-photos-app#39] opened 2021-05-29 04:42 UTC
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet#5

**In which task and step of the codelab can this issue be found?**
Object declarations

**Describe the problem**
In the sentence: "Each time your app calls MarsApi.retrofitService, the caller will access the same a singleton Retrofit object that implements MarsApiService which is created on the first access." it seem that the 'a' in "the same a singleton Retrofit object" is not necessary.

**Steps to reproduce?**
As stated above.

**Versions**
Not applicable.

**Additional information**
Nil.

**Comment by osuleymanova** [comment] 2021-11-17 23:38
Duplicate of #22

**Comment by osuleymanova** [comment] 2021-11-30 21:38
@KKH-tw 
Thank you for reaching out to us. The issue is fixed and published.

**Closed as completed by osuleymanova** 2021-11-30 21:38 UTC
