### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by svitlana-shumilova** [google-developer-training/android-basics-kotlin-mars-photos-app#91] opened 2021-11-04 20:31 UTC
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#2

**In which task and step of the codelab can this issue be found?**
There is wrong screenshot in the end of 'Update the ViewModel' paragraph. It should be a screenshot with a url address, but instead there is a screenshot with an error message.

![actual](https://user-images.githubusercontent.com/40916369/140415320-dc3da2c1-df93-4f4f-ad62-034886b842bb.png)
![expected](https://user-images.githubusercontent.com/40916369/140415323-f8b21387-fa2e-46fc-ad3c-8888802dbfc4.png)

**Describe the problem**

**Comment by osuleymanova** [comment] 2021-11-16 20:40
Duplicate of #82, #74, #70, #56

**Comment by osuleymanova** [comment] 2022-04-12 23:42
@mongolian-spy 
Thank you for reaching out to us. The image in the codelab was updated:
![Screen Shot 2022-04-12 at 2 45 40 PM](https://user-images.githubusercontent.com/86437155/163071910-fc1d6888-6938-4a2c-ba7b-a2f1ce45104a.png)

**Closed as completed by osuleymanova** 2022-04-12 23:42 UTC
