### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by tsrrus** [google-developer-training/android-basics-kotlin-mars-photos-app#96] opened 2021-11-12 12:28 UTC
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''
---

https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images#3

"Add Recyclerview" task, step #8.

The step text talks:
"... You can achieve this with a combination of padding in fragment_overview.xml layout and in gridview_item.xml layout."
but the real grid view file name in the source code package is "grid_view_item.xml", with an additional underscore.

**Comment by osuleymanova** [comment] 2021-11-16 21:14
Duplicate of #48

**Comment by osuleymanova** [comment] 2022-04-13 00:28
@tsrrus 
Thank you for reaching out to us. The typo was fixed:
![Screen Shot 2022-04-12 at 3 39 57 PM](https://user-images.githubusercontent.com/86437155/163075779-ff9fda16-6811-46be-868c-7691066a41bb.png)

**Closed as completed by osuleymanova** 2022-04-13 00:28 UTC
