### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by cScocco** [google-developer-training/android-basics-kotlin-mars-photos-app#32] opened 2021-05-18 14:55 UTC
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#6

**In which task and step of the codelab can this issue be found?**
7. Add Internet permission and Exception Handling - Android Permissions - step 2

**Describe the problem**
the app still crashed with 2error socket failed eperm (operation not permitted)"
In order to fix it, I had to disinstall the app from the emulator and reinstall it

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-04-15 22:08
@cScocco 
Thank you for reaching out to us. The issue is not reproducible on my end. I really appreciate if you provide screenshots clarifying the problem.

**Comment by osuleymanova** [comment] 2022-05-10 18:47
The issue is closed as no further clarification was provided.

**Closed as completed by osuleymanova** 2022-05-10 18:47 UTC
