### ISSUE TITLE
Android Basics: Coroutines

### ISSUE THREAD

**Issue by matttzzz** [google-developer-training/android-basics-kotlin-mars-photos-app#97] opened 2021-11-13 07:10 UTC
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-introduction-coroutines?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-introduction-coroutines#1

**In which task and step of the codelab can this issue be found?**
First step

**Describe the problem**
fun main() {
    val thread = Thread {
        println("${Thread.currentThread()} has run.")
    }
    thread.start()
}

Typing the above  into Kotlin playground returns an error:

Exception in thread "main" java.io.FileNotFoundException: /var/task/tmp/35f8e30675644945a16475c7aee06c7a/executor.policy (No such file or directory)
 at java.io.FileOutputStream.open0 (FileOutputStream.java:-2) 
 at java.io.FileOutputStream.open (FileOutputStream.java:270) 
 at java.io.FileOutputStream.<init> (FileOutputStream.java:213) 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-04-14 23:18
@matttzzz 
Thank you for reaching out to us. The issue is closed as not reproducible:
![Screen Shot 2022-04-14 at 4 14 44 PM](https://user-images.githubusercontent.com/86437155/163492216-9382b2f2-d9c3-473a-af4f-24ba7dc04ed4.png) 
No error observed.

**Closed as completed by osuleymanova** 2022-04-14 23:18 UTC
