### ISSUE TITLE
Android Basics: Load and display images from the Internet, wrong application name 'marsrealestate'

### ISSUE THREAD

**Issue by ommos61** [google-developer-training/android-basics-kotlin-mars-photos-app#172] opened 2023-02-23 16:22 UTC
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue: use of marsrealestate instead of marsphotos'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images#3
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images#4

**In which task and step of the codelab can this issue be found?**
ListAdapter (Refresher), step 4
Add the binding adapter and connect the parts, step 4
Add a binding adapter for the status ImageView, step1

**Describe the problem**
In the describing text on the codelabs pages, in the above three location the application name 'marsrealestate' is used, which should be 'marsphotos'.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Not applicable
_API version of the emulator:_ Not applicable

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2023-04-10 22:08
Hello @ommos61,

Thank you for reaching out to us. The typo is fixed and will be published soon.

**Comment by osuleymanova** [comment] 2023-04-10 22:09
Duplicate of #170

**Closed as completed** 2023-07-25 21:59 UTC
